Exception on /delete_chromebook/7 [POST]
Traceback (most recent call last):
  File "C:\Users\Danny\Documents\Projects\Applications\chromebookloansystem\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1932, in _exec_single_context
    self.dialect.do_executemany(
  File "C:\Users\Danny\Documents\Projects\Applications\chromebookloansystem\venv\Lib\site-packages\sqlalchemy\dialects\postgresql\psycopg2.py", line 773, in do_executemany
    cursor.executemany(statement, parameters)
psycopg2.errors.NotNullViolation: null value in column "chromebook_id" of relation "chromebook_history" violates not-null constraint
DETAIL:  Failing row contains (1, null, Bob, 2023-09-22 17:39:06.729434, Loaned).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Danny\Documents\Projects\Applications\chromebookloansystem\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Danny\Documents\Projects\Applications\chromebookloansystem\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Danny\Documents\Projects\Applications\chromebookloansystem\venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Danny\Documents\Projects\Applications\chromebookloansystem\venv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Danny\Documents\Projects\Applications\chromebookloansystem\app.py", line 217, in delete_chromebook
    db.session.commit()
  File "C:\Users\Danny\Documents\Projects\Applications\chromebookloansystem\venv\Lib\site-packages\sqlalchemy\orm\scoping.py", line 553, in commit
    return self._proxied.commit()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Danny\Documents\Projects\Applications\chromebookloansystem\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1905, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "C:\Users\Danny\Documents\Projects\Applications\chromebookloansystem\venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Danny\Documents\Projects\Applications\chromebookloansystem\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1220, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "C:\Users\Danny\Documents\Projects\Applications\chromebookloansystem\venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Danny\Documents\Projects\Applications\chromebookloansystem\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1195, in _prepare_impl
    self.session.flush()
  File "C:\Users\Danny\Documents\Projects\Applications\chromebookloansystem\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4153, in flush
    self._flush(objects)
  File "C:\Users\Danny\Documents\Projects\Applications\chromebookloansystem\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4289, in _flush
    with util.safe_reraise():
  File "C:\Users\Danny\Documents\Projects\Applications\chromebookloansystem\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\Danny\Documents\Projects\Applications\chromebookloansystem\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4250, in _flush
    flush_context.execute()
  File "C:\Users\Danny\Documents\Projects\Applications\chromebookloansystem\venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 467, in execute
    rec.execute(self)
  File "C:\Users\Danny\Documents\Projects\Applications\chromebookloansystem\venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 644, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\Users\Danny\Documents\Projects\Applications\chromebookloansystem\venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 85, in save_obj
    _emit_update_statements(
  File "C:\Users\Danny\Documents\Projects\Applications\chromebookloansystem\venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 904, in _emit_update_statements
    c = connection.execute(
        ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Danny\Documents\Projects\Applications\chromebookloansystem\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1413, in execute
    return meth(
           ^^^^^
  File "C:\Users\Danny\Documents\Projects\Applications\chromebookloansystem\venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 483, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Danny\Documents\Projects\Applications\chromebookloansystem\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1637, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Danny\Documents\Projects\Applications\chromebookloansystem\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1841, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Danny\Documents\Projects\Applications\chromebookloansystem\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1982, in _exec_single_context
    self._handle_dbapi_exception(
  File "C:\Users\Danny\Documents\Projects\Applications\chromebookloansystem\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\Danny\Documents\Projects\Applications\chromebookloansystem\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1932, in _exec_single_context
    self.dialect.do_executemany(
  File "C:\Users\Danny\Documents\Projects\Applications\chromebookloansystem\venv\Lib\site-packages\sqlalchemy\dialects\postgresql\psycopg2.py", line 773, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) null value in column "chromebook_id" of relation "chromebook_history" violates not-null constraint
DETAIL:  Failing row contains (1, null, Bob, 2023-09-22 17:39:06.729434, Loaned).

[SQL: UPDATE chromebook_history SET chromebook_id=%(chromebook_id)s WHERE chromebook_history.id = %(chromebook_history_id)s]
[parameters: [{'chromebook_id': None, 'chromebook_history_id': 1}, {'chromebook_id': None, 'chromebook_history_id': 2}, {'chromebook_id': None, 'chromebook_history_id': 3}, {'chromebook_id': None, 'chromebook_history_id': 4}]]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
